{{- if and .Values.persistence.uploads.enabled (not .Values.persistence.uploads.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "discourse.uploadsPvcName" . }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    {{- toYaml .Values.persistence.uploads.accessModes | nindent 4 }}
  {{- if .Values.persistence.uploads.storageClass }}
  storageClassName: {{ .Values.persistence.uploads.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
{{- end }}
---
{{- if and .Values.persistence.backups.enabled (not .Values.persistence.backups.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "discourse.backupsPvcName" . }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    {{- toYaml .Values.persistence.backups.accessModes | nindent 4 }}
  {{- if .Values.persistence.backups.storageClass }}
  storageClassName: {{ .Values.persistence.backups.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size }}
{{- end }}
