{{- if include "discourse.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discourse.secretName" . }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.discourse.database.password (not .Values.discourse.database.existingSecret) }}
  {{ .Values.discourse.database.secretKey }}: {{ .Values.discourse.database.password | quote }}
  {{- end }}
  {{- if and .Values.discourse.smtp.password (not .Values.discourse.smtp.existingSecret) }}
  {{ .Values.discourse.smtp.secretKey }}: {{ .Values.discourse.smtp.password | quote }}
  {{- end }}
  {{- if and .Values.discourse.secretKeyBase.value (not .Values.discourse.secretKeyBase.existingSecret) }}
  {{ .Values.discourse.secretKeyBase.secretKey }}: {{ .Values.discourse.secretKeyBase.value | quote }}
  {{- end }}
  {{- if and .Values.discourse.admin.password (not .Values.discourse.admin.existingSecret) }}
  {{ .Values.discourse.admin.secretKey }}: {{ .Values.discourse.admin.password | quote }}
  {{- end }}
{{- end }}
